  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ensign-weather-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: ensign-weather 
    template:
      metadata:
        labels:
          app: ensign-weather 
      spec:
        containers:
        - name: weather 
          image: us-central1-docker.pkg.dev/ensign-421602/ensign-public/weather:extra
          ports:
          - containerPort: 5555 
